/**
 * Verifies GET /me/disruptions returns a disruption generated by the worker job.
 */
import { afterAll, beforeAll, expect, test } from "bun:test";
import { eq } from "drizzle-orm";
import type { Database } from "@route-helper/db";
import { routes, users } from "@route-helper/db";
import type { FastifyInstance } from "fastify";

import { createIntegrationApp, describeIntegration, jwtSecret, minimalRouteCreateBody } from "./helpers.js";
import { signAccessToken } from "../src/lib/jwtTokens.js";
import { hashPassword } from "../src/lib/scryptPassword.js";
import { runDueRouteChecks } from "../../worker/src/jobs/runDueRouteChecks.js";

describeIntegration("GET /me/disruptions (integration)", () => {
  let app: FastifyInstance;
  let db: Database;
  let userId: string;
  let routeId: string;
  const marker = `integration-disruption-${Date.now()}`;

  beforeAll(async () => {
    const created = await createIntegrationApp();
    app = created.app;
    db = created.db;

    const email = `disruption-test-${Date.now()}@example.com`;
    const [u] = await db
      .insert(users)
      .values({
        email,
        passwordHash: hashPassword("test-password-12345"),
        displayName: "Disruption test user",
      })
      .returning({ id: users.id });
    if (!u) {
      throw new Error("Failed to insert test user");
    }
    userId = u.id;

    const routeBody = minimalRouteCreateBody("Disruption test route", `${marker}-route`);
    const [r] = await db
      .insert(routes)
      .values({
        userId,
        name: routeBody.name,
        startTime: routeBody.startTime,
        expectedArrival: routeBody.expectedArrival,
        timezone: routeBody.timeZone,
        departureLabel: routeBody.departureLabel,
        destinationLabel: routeBody.destinationLabel,
        origin: routeBody.origin,
        destination: routeBody.destination,
        transitSnapshot: routeBody.transitSnapshot,
        daysOfWeek: routeBody.daysOfWeek,
      })
      .returning({ id: routes.id });
    if (!r) {
      throw new Error("Failed to insert test route");
    }
    routeId = r.id;

  });

  afterAll(async () => {
    await db.delete(users).where(eq(users.id, userId));
    await app.close();
  });

  test("returns worker-generated disruption for authenticated user", async () => {
    const now = new Date("2026-06-01T05:56:00.000Z");
    await runDueRouteChecks({
      db,
      googleApiKey: "integration-test-key",
      now,
      evaluateRouteCheck: async () => ({
        ok: false,
        summary: marker,
        durationSeconds: 1800,
      }),
      suggestAlternativeRoute: async () => ({
        id: "alt-1",
        label: "25 min",
        durationSeconds: 1500,
        savingsSeconds: 300,
        payload: {},
        summary: "Saves about 5 min with 25 min",
      }),
      sendPushNotification: async () => {
        // This test only cares that the worker persists the disruption.
      },
    });

    const token = signAccessToken(jwtSecret, {
      sub: userId,
      email: "disruption-test@example.com",
    });

    const res = await app.inject({
      method: "GET",
      url: "/me/disruptions",
      headers: { authorization: `Bearer ${token}` },
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as Array<{
      id: string;
      description: string;
      severity: string;
      occurredAt: string;
      affectedRoutes: string[];
      routeId: string | null;
      suggestedAlternative?: { id: string; savingsSeconds: number } | null;
    }>;
    expect(Array.isArray(body)).toBe(true);
    const found = body.find((row) => row.routeId === routeId && row.description.includes(marker));
    expect(found).toBeDefined();
    expect(found?.description).toContain(marker);
    expect(found?.description).toContain("Disruption test route");
    expect(found?.severity).toBe("warn");
    expect(typeof found?.occurredAt).toBe("string");
    expect(Array.isArray(found?.affectedRoutes)).toBe(true);
    expect(found?.routeId).toBe(routeId);
    expect(found?.suggestedAlternative).toMatchObject({ id: "alt-1", savingsSeconds: 300 });
    expect(found?.affectedRoutes).toEqual(["Disruption test route"]);
  });
});
